language: node_js
node_js:
  - '8'
notifications:
  email: false
branches:
  only:
    - source
cache:
  yarn: true
script:
  - cd website
  - yarn install && yarn test && yarn build
before_deploy:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - export GIT_USER="${GH_NAME}"
deploy:
  provider: script
  skip_cleanup: true
  script: yarn run publish-gh-pages
  on:
    branch: source