language: node_js
node_js:
  - '8'
notifications:
  email: false
branches:
  only:
    - source
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website
  - yarn install && yarn test && GIT_USER="${GH_NAME}" yarn run publish-gh-pages